### ISSUE TITLE
As someone interested in obtaining a Christmas tree permit, I should see precise language about tree cutting limits, so that I understand the limit on the number of trees I can cut

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#139]
## Notes
Under Cost it reads, “Christmas trees cost $5.00 each, and a household is allowed to cut up to 3 trees per permit.” 

The “per permit” language implies there is no limit on how many permits a person or household can obtain.

It should read, “Christmas trees cost $5.00 each, and a household is allowed to cut up to 3 trees.” 

## Acceptance Criteria
- [ ] There are no instances of "up to X trees per permit" in the app (including on the permit itself, and in the email)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit  Filed PR's for the on site changes, but do not know where to make changes for email and printable permit
