### ISSUE TITLE
Regular DB backups

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#174]
## Acceptance Criteria
- [ ] check if not implemented
- [ ] follow up on regular push back to this

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Is this in reference to SUDS?

**Comment by msadakFS** [comment]
@lauraGgit can you explain the scope of the regular DB backups? Is this a line item to add to the production checklist covered in #280?

**Comment by lauraGgit** [comment]
Right now we have to rely on Cloud.gov to pull a db back up for us, but if we have data loss issues, it could take a bit to restore the data, with our own DB backups, we can have more readily accessible, higher frequency db backups.

**Comment by ASprinkle** [comment]
Closing issue based on suggestion in the comments ^
