### ISSUE TITLE
As a developer, I should be able to change the season dates when I am developing locally.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#346]
## Notes
This is not yet an issue on staging, but appears to multiple developers. When they change an ARP season date it does not show up on the ARP's page, and the ability to buy the permit does not appear. This does seem to work for other forests.

## Acceptance Criteria
- [x] a developer can enable the season for the ARP when testing on a local server

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
As noted in Slack, I am able to change ARP season date and the buy function appears to work.

**Comment by lauraGgit** [comment]
@mtlaney are you able to take a look at this one?

**Comment by mtlaney** [comment]
@lauraGgit sure thing!

**Comment by mtlaney** [comment]
@lauraGgit Here's where we are. I can get to successfully POST to /admin/christmas-trees/forests/1
<img width="487" alt="screen shot 2018-09-18 at 12 30 59 pm" src="https://user-images.githubusercontent.com/18233188/45702031-babb3e80-bb3e-11e8-984a-d02c59a4d92f.png">

It will also successfully update my local DB:
<img width="597" alt="screen shot 2018-09-18 at 12 32 07 pm" src="https://user-images.githubusercontent.com/18233188/45702091-e50cfc00-bb3e-11e8-8ca5-62e566b98c4b.png">

However locally it looks like the data is being fed by 01-christmasTreesForests.js from the seeders in server, and am unable to update. 

Any chance it could be blocked somewhere by the forced Request a Content Change redirect locally that I'm not seeing?

**Comment by lauraGgit** [comment]
@adborden would you be able to take a look at this?

**Comment by lauraGgit** [comment]
on the server it looks like its this  controller: https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/controllers/christmas-tree-admin.es6#L157

and on the frontend: https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/app/trees/admin/season-dates/season-dates.component.ts#L112

**Comment by adborden** [comment]
:eyes:

**Comment by adborden** [comment]
Surprise! We're mocking it out in local/CI. A nasty surprise in my opinion. Do you know if it's necessary? I'd like to take it out. Otherwise, make it less likely to trip up developers.

https://github.com/18F/fs-open-forest-platform/blob/77236d2f9ca97ad7a2b3374d90698a2eb6f5966a/server/src/models/christmas-trees-forests.es6#L111

**Comment by lauraGgit** [comment]
Oooooh! I think this was because the admin ability to change the dates was a later feature add, so there was some way to open up a season more easily when you were working development and also in CI.

I think we can go ahead and rip that, but we'll likely have to update all the e2e xmas tests so that all the tests that run against the xmas tree work flow have open seasons.

**Comment by adborden** [comment]
+1 I'll remove it and update the tests.

**Comment by adborden** [comment]
I have one more PR coming on this one that will give us a separate test database.

**Comment by lauraGgit** [comment]
@adborden looks like the change to parse out the database url from the vcap didn't work for the sequelize migrations during deployment. We might want to revert how the database url gets parsed in `./server/.sequelize.js`

**Comment by lauraGgit** [comment]
Also got an error that postgres doesn't support `db:create`
