### ISSUE TITLE
As a special use repeat applicant, i should be able to repopulate my applicant contact information with data from a previous application.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#347]
## Notes
This came from one of the scale up stories, and could be useful. Definitely not necessary for production.

## Acceptance Criteria
- [ ] An applicant that has previously submitted an application, can pre-populate the contact information with contact info submitted in a prior application. 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This issue is redundant with #398
