### ISSUE TITLE
BUG: Login.gov does not work on staging

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-open-forest-platform#352]
## Notes
![image.png](https://images.zenhubusercontent.com/5b16b7b789d5dc41604fe1e0/76e2c398-ae8d-4c1c-965b-b3b4e1226c27)

## Acceptance Criteria
- [ ] Can log in using login.gov on staging

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Login.gov folks investigating on this. Our configuration should not have changed recently.

**Comment by lauraGgit** [comment]
Need to either update uri in Login.gov dashboard or https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/auth/login-gov.es6#L35 so that the two uris are exact matches.

**Comment by lauraGgit** [comment]
Confirmed - need to update the dashboard config.

**Comment by lauraGgit** [comment]
updated dashboard config & now appears to be working on staging.
