### ISSUE TITLE
As a user, I should not have to enter a fax number if I do not have one

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-open-forest-platform#355]
## Notes
I accidentally entered a number into the Fax # box on the outfitter guide form. I deleted the number. I was not able to submit the application and it gave the error below. I was forced to enter a fake fax number in order to submit the application.

![image.png](https://images.zenhubusercontent.com/5b16b7b789d5dc41604fe1e0/fd7eaa71-2cae-49d1-8ef3-5ff89613cb9c)

## Acceptance Criteria
- [ ] User can delete a fax number and still submit the application

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
@mtlaney is on this

**Comment by msadakFS** [comment]
Am still getting the error, moving back to Open PR

**Comment by lauraGgit** [comment]
Ah it looks like we need to update the server validation in the temp Outfitter model in the server @mtlaney https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/models/tempoutfitter-application.es6#L406

**Comment by mtlaney** [comment]
@msadakFS can you give me steps to reproduce, I cannot generate the error on staging. 
Server side validation shows it as nullable. 
I've tried entering no fax number, entering full than deleting, entering 3 or 4 than deleting, etc.

**Comment by msadakFS** [comment]
@mtlaney Enter in a fax number, delete that number, then try to submit the application. It will not submit unless a fax number gets entered. So if a user accidentally enters a number in that box, they are now committed to entering a number.

**Comment by mtlaney** [comment]
@msadakFS hmmm, that's what I tried, I'll give it another shot

**Comment by msadakFS** [comment]
The error is no longer occurring. Strange. I tested it a number of times and was consistently getting the error. I will close this issue.
