### ISSUE TITLE
during logout, the redirect URL doesn't match the redirect

### ISSUE THREAD

**Issue by annepetersen** [18F/fs-open-forest-platform#359]
## Notes
Usability test participant logged out, then clicked on the link from the email and got logged back in somehow.

## Acceptance Criteria
- [ ] Log out action should log you out entirely: both app and login.gov
- [ ] Should not be able to see permit application nor any PII from the link in the email without logging in
- [ ] Redirect URL should match the redirect

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
This is now applicable in PROD too.

**Comment by lauraGgit** [comment]
Getting a connection refused response. Likely need to update the firewall rule.

**Comment by lauraGgit** [comment]
For prod this PR: https://github.com/18F/identity-idp/pull/2552/files
