### ISSUE TITLE
As a user, I would like to be able to open email attachment to print out my permit. (Cannot open attachment that was received for Christmas Tree Permit (thus could not print permit)  )

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest-platform#360]
## Notes
Cannot open attachment that was received for Christmas Tree Permit (thus could not print permit)  Also there is a long link attached to email to go to a site to get permit "•	Your permit is available for printing from https://forest-service-trees-staging.app.cloud.gov/christmas-trees/forests/arp/applications/permits/5b4c5d58-dbe1-408f-9dbf-745744d89aae?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNWI0YzVkNTgtZGJlMS00MDhmLTlkYmYtNzQ1NzQ0ZDg5YWFlIiwiaWF0IjoxNTM3Nzk0OTAzLCJhdWQiOiJmcy10cmVlcy1wZXJtaXQtYXBpLXVzZXJzIiwiaXNzIjoidHJlZXMtcGVybWl0LWFwaSIsInN1YiI6ImNocmlzdG1hcyB0cmVlIHBlcm1pdCBvcmRlcnMifQ.v6izUG0bv8VeSuzLUmHDao2pID7qlhsk6oQYvhP1bME or in an attachment to this email."
![Xmastree screenshot.PNG](https://images.zenhubusercontent.com/58a603a251aa2c305774a9ca/7ccc312c-6922-4db0-b4d2-93c916caa7fc)
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
I wonder if we want to wait on this until we switch over to the new USDA email?

**Comment by msadakFS** [comment]
@lauraGgit That is a good idea. I wonder when USDA email will be ready? It's been week to week for quite a while.

**Comment by lauraGgit** [comment]
Can confirm that this is now  attaching a permit
