### ISSUE TITLE
As a user, I should be able to view my submitted information by clicking the link in the confirmation email

### ISSUE THREAD

**Issue by annepetersen** [18F/fs-open-forest-platform#375]
## Notes
Usability test participants tried to click a link in the email that said "View your undefined here" which is in the spot where they should be able to view what they just submitted and got a 404 page after a brief view of something that looked like it should've been their info. 

Screenshot: 
<img width="554" alt="outfitters email" src="https://user-images.githubusercontent.com/5359122/46432064-ecbdca80-c712-11e8-8642-58f25162294e.png">

## Acceptance Criteria
- [ ] Link is named appropriately in email
- [ ] Link from email works

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
ah, ok, so the frontend once it gets a `200` from the file update then sends a `Submitted` email update to the `server` so this should probably not send the submitted email until that is followed. so it should probably use the comoncontroller.updateemailswitch to generate the temp submitted email.

**Comment by lauraGgit** [comment]
Confirmed can access in staging
