### ISSUE TITLE
As a temp outfitter applicant, if my dates are accepted by the application they should not show up as "Invalid date" in the confirmation email

### ISSUE THREAD

**Issue by annepetersen** [18F/fs-open-forest-platform#376]
## Notes
Usability test participants received confirmation emails that listed "Invalid dates" even though they were able to successfully submit them online with no errors (and they seem to be valid dates). 

Screenshot:
<img width="554" alt="outfitters email" src="https://user-images.githubusercontent.com/5359122/46432064-ecbdca80-c712-11e8-8642-58f25162294e.png">

## Acceptance Criteria
- [ ] Dates input by users are listed accurately in confirmation email
- [ ] "Invalid date" does not appear in the email (this shouldn't be possible)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Outfitter guide apps do not require a time.

**Comment by ASprinkle** [comment]
I was going to test this, but I got a fail in the application process for noncommercial group use regarding the character limit for my email address.. thoughts?
![suncguappfail](https://user-images.githubusercontent.com/33435621/47871874-61476000-ddca-11e8-9daa-246bfd255eef.png)

**Comment by lauraGgit** [comment]
@ASprinkle did you put in a very long email or we it not that long?

**Comment by ASprinkle** [comment]
[SU error.docx](https://github.com/18F/fs-open-forest-platform/files/2539675/SU.error.docx)
I manually entered my email address, and received the error. Attached screen shots in doc

**Comment by lauraGgit** [comment]
I just put in a couple of applications  and could not replicate this error.

**Comment by lauraGgit** [comment]
@ASprinkle would you be able to try submitting a temp outfitter application to see if the email gives you the correct time in the email, and separately submit a noncommericial to see if you are still receiving this error.

**Comment by ASprinkle** [comment]
@lauraGgit I tested non-commercial group and temp OG. I was able to go through the process for both, without an issue. I received an email for both and all of the information was accurate.
