### ISSUE TITLE
As a xmas tree user, I want to see no typos!

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#386]
## Acceptance Criteria
- [x] fix "it's" vs. "its" in cutting information

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
PO reviewed - applied to all NFs under How to cut your tree - Helpful cutting tips.
