### ISSUE TITLE
As an arapahoe xmas tree cutter, I want an up-to-date map

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#404]
## Notes
ARP wants to upload a new map, but its not quite ready yet

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
The ARP has a new Canyon Lakes cutting area map. The site needs to be updated with this new map. 
[ARP Canyon Lakes XmasTreeMap 20181023.pdf](https://github.com/18F/fs-open-forest-platform/files/2525668/ARP.Canyon.Lakes.XmasTreeMap.20181023.pdf)

**Comment by lauraGgit** [comment]
@ASprinkle do you think that this Alternative Text is still accurate? https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/assets/content/arp/map-alt-text/red-feather-lakes.md

**Comment by ASprinkle** [comment]
After "smokey bear lane is the first cutting area road that is one-way towards the west and is 1.4 miles long.
Insert "The junction for Donner way is about half way down Smokey Bear lane, is a one-way road to the south and west and ties into Comet lane."

The rest of it looks like it is still accurate.

**Comment by ASprinkle** [comment]
PO reviewed on staging. Closing.
