### ISSUE TITLE
As a ARP buyer, I want to buy at the correct price

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#407]
## Notes
bump up the ARP price to $20 

## Acceptance Criteria
- [x] xmas trees are $20 in prod on ARP :money:

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Updated on POSS, now updating on Open Forest

**Comment by ASprinkle** [comment]
I reviewed on staging. $20 price was consistent through the site and Pay.gov. Closing.
