### ISSUE TITLE
Error processing credit card payment for Christmas Tree permit 

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest-platform#415]
## Notes
Received errror trying to mayke payment on a tree at Shsoshone at about 1:30 EST 10/31/2018

## Acceptance Criteria
- [x] Able to make a real Shoshone Christmas tree permit purchase without error.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@aaronburk has this been tested again?

**Comment by aaronburk** [comment]
I will test on Monday and we can see if the pay.gov/POSS problem is also fixed

**Comment by ASprinkle** [comment]
Aaron tested today, I observed. Updated acceptance criteria & checked the box. Purchase was successful.
