### ISSUE TITLE
As a user I want to see an email from Open Forest once I have completed the purchase process for my Christmas tree permit.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#435]
## Notes
I performed three tests on staging site, completed the pay.gov process, and received no email to my inbox.

## Acceptance Criteria
- [ ] An email containing the permit and permit rules is received promptly after pay.gov purchase process is completed.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Confirmed that email is working on staging for special uses.

**Comment by lauraGgit** [comment]
Note: same cause and remediation as #434.

@ASprinkle I bought a test permit and was able to receive an email. Can you please confirm?

**Comment by ASprinkle** [comment]
Yes, I just verified this when offering a demo to folks on the Shoshone.
