### ISSUE TITLE
Typedocs error preventing correct build

### ISSUE THREAD

**Issue by annepetersen** [18F/fs-open-forest-platform#437]
## Notes
Typedocs is 404ing: fix to correct build errors

<img width="717" alt="typedoc 404" src="https://user-images.githubusercontent.com/5359122/48139487-3b0f3d80-e26c-11e8-9f9e-2999a8bfca7a.png">

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Verified that this was a documentation error-  and will update the documentation as part of remediating the builds in #428
