### ISSUE TITLE
Post-government shutdown, reinstate the Open Forest site.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#480]
## Notes
If the government shuts down on Dec. 21, the Open Forest site will not be available for the public.
When the potential government shut down ends, we would need to reinstate the Open Forest site so that: 
    - people to purchase Christmas tree tags if it is still Christmas tree season, or so that
    - people to learn about the Christmas tree program (without the buy permit button) if it is no longer Christmas tree season.

## Acceptance Criteria
- [x]  The Open Forest website is accessible, and functioning.
- [x]  Forest visitors can engage in the buy permit process if the Christmas tree season is still open.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@davemcorwin @lauraGgit  Checking in on this - Is there anything I need to approve or do as a next step to reopen the Open Forest site?

**Comment by lauraGgit** [comment]
@ASprinkle / @davemcorwin looks like with the latest changes this is good to go. Feel free to click merge on #524

**Comment by ASprinkle** [comment]
I am "not authorized to merge" it.
