### ISSUE TITLE
As a developer I want to rename the configured app names to reduce cognitive burden when accomplishing tasks.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#528]
## Notes
Use configured application names that correspond to our nomenclature.

## Acceptance Criteria
- [x] No change

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [] Compare finished design with mockup
- [] Usability tested

**Comment by suprenant** [comment]
From standup, this is ready to go pending some cloud.gov work.
