### ISSUE TITLE
As a developer, I want to control the url of the production platform api

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#544]
## Notes
Specify the prouction api host so Cloud.gov does not assign one since this needs to be configured in the front end.

## Acceptance Criteria
- [ ] Deployments succeed and application is available

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
From stand up: waiting approval for PR
