### ISSUE TITLE
As a public user I would need to authenticate using USDA approved eAuth for Special User permits at the Mount Baker Snoqualmie

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest-platform#571]
## Notes
We currently use login.gov to perform this authentication but due to cyber security concerns we are unable to implement this in production.  We need to use the USDA approved eAuth system for user authentication

## Acceptance Criteria
- User can be authenticated and gain access to the MBS special use OPen FOrest system using eAuth.

## Tasks
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by DawnDesigner** [comment]
OBE when decided to stick with Login.gov
