### ISSUE TITLE
Problem getting past front page for MBS SU permit application

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest-platform#586]
## Notes
As a user when I go to the MBS special use page and click on any of 3 options on the first page nothing happens.  As an administrator user the same thing happens.  If then lgoin as an admin then go to the upper right and click "review applications"  then from that screen click the button submit another application it asend me back to the front page at which point I can then click any fornt page buttong and get access to the system

## Acceptance Criteria
- When a user goes to front page they should be able to click and get information without being admin and without having to be rerouted

## Tasks
- Fix issues with accessing information and application form front page
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
@aaronburk was this in prod or staging?

**Comment by ASprinkle** [comment]
I could not recreate the errors that initially described this issue.
