### ISSUE TITLE
Incorrect URL on Github Repo

### ISSUE THREAD

**Issue by sfred** [18F/fs-open-forest-platform#590]
## Notes
The URL on the fs-open-forest-platform GitHub repo (https://openforest.fs.udsa.gov), is incorrect. The URL should be updated to https://openforest.fs.usda.gov.

**Comment by davemcorwin** [comment]
Done :) https://github.com/18f/fs-open-forest-platform

**Comment by ASprinkle** [comment]
I'll Move this to Ready for Master for now, but something tells me I can just close it at this point, and that "done" means it was a quick simple fix. Correct? :)  I am also guessing this was the URL at the top of the page...?

**Comment by sfred** [comment]
It was the URL on top of the page. I'll close the issue.
